name: Terraform Infrastructure Provisioning

on:
  pull_request:
    branches:
      - staging  # Change to your target branch
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
            role-to-assume: arn:aws:iam::681117582889:role/GitActionPermissionPolicy #change to reflect your IAM role’s ARN
            role-session-name: GitHub_to_AWS_via_FederatedOIDC

                  
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.9.8 # Specify the version you need
          
      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Plan Terraform
        id: plan
        run: terraform plan -out=tfplan

      - name: Apply Terraform
        run: |
          terraform apply -auto-approve tfplan
        continue-on-error: true  # Continue even if apply fails for status check

      - name: Check Terraform Status
        run: |
          if [ $? -ne 0 ]; then
            echo "Terraform apply failed"
            exit 1
          else
            echo "Terraform apply succeeded"
          fi
